version: '3.7'
services:
    postgres:
      image: postgres
      container_name: postgres
      restart: always
      env_file:
        - .env
      logging:
        options:
          max-size: 10m
          max-file: "3"
      ports:
        - '5438:5432'
      volumes:
        - ./postgresql.conf:/etc/postgresql/postgresql.conf
        - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
        - ./sql/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
      command: postgres -c config_file=/etc/postgresql/postgresql.conf
      networks:
        - database

    pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin
      env_file:
        - .env
      ports:
        - "16543:80"
      depends_on:
        - postgres
      networks:
        - database

networks: 
  database:
    driver: bridge