apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: harbor-nfs-sc
provisioner: nfs.csi.k8s.io
parameters:
  server: 10.0.2.206
  share: /
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1