
#----------------------------------
# Volume harbor-registry
#----------------------------------
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-registry
spec:
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: harbor-nfs-sc
  mountOptions:
    - nfsvers=4.1
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    volumeHandle: unique-volumeid  
    volumeAttributes:
      server: 10.0.2.2
      share: /

#----------------------------------
# Volume harbor-jobservice
#----------------------------------
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-jobservice
spec:
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: harbor-nfs-sc
  mountOptions:
    - nfsvers=4.1
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    volumeHandle: unique-volumeid  
    volumeAttributes:
      server: 10.0.2.2
      share: /


#----------------------------------
# Volume harbor-jobservice-scandata
#----------------------------------
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-jobservice-scandata
spec:
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: harbor-nfs-sc
  mountOptions:
    - nfsvers=4.1
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    volumeHandle: unique-volumeid  
    volumeAttributes:
      server: 10.0.2.2
      share: /

#----------------------------------
# Volume harbor-chartmuseum
#----------------------------------
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-chartmuseum
spec:
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: harbor-nfs-sc
  mountOptions:
    - nfsvers=4.1
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    volumeHandle: unique-volumeid  
    volumeAttributes:
      server: 10.0.2.2
      share: /

#----------------------------------
# Volume data-harbor-trivy-0
#----------------------------------
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-harbor-trivy-0
spec:
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: harbor-nfs-sc
  mountOptions:
    - nfsvers=4.1
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    volumeHandle: unique-volumeid  
    volumeAttributes:
      server: 10.0.2.2
      share: /


#----------------------------------
# Volume data-harbor-redis-0
#----------------------------------
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-harbor-redis-0
spec:
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: harbor-nfs-sc
  mountOptions:
    - nfsvers=4.1
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    volumeHandle: unique-volumeid  
    volumeAttributes:
      server: 10.0.2.2
      share: /