---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-registry
  namespace: harbor
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: harbor-registry
  storageClassName: harbor-nfs-sc
  volumeMode: Filesystem
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-registry
spec:
  capacity:
    storage: 6Gi
  nfs:
    server: ip do servidor nfs
    path: /
  accessModes:
    - ReadWriteMany
  claimRef:
    kind: PersistentVolumeClaim
    namespace: harbor
    name: harbor-registry
    apiVersion: v1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: harbor-nfs-sc
  volumeMode: Filesystem
# harbor-jobservice
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-jobservice
  namespace: harbor
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: harbor-jobservice
  storageClassName: harbor-nfs-sc
  volumeMode: Filesystem
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-jobservice
spec:
  capacity:
    storage: 6Gi
  nfs:
    server: ip do servidor nfs
    path: /
  accessModes:
    - ReadWriteMany
  claimRef:
    kind: PersistentVolumeClaim
    namespace: harbor
    name: harbor-jobservice
    apiVersion: v1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: harbor-nfs-sc
  volumeMode: Filesystem


  # harbor-jobservice-scandata
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-jobservice-scandata
  namespace: harbor
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: harbor-jobservice-scandata
  storageClassName: harbor-nfs-sc
  volumeMode: Filesystem
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-jobservice-scandata
spec:
  capacity:
    storage: 6Gi
  nfs:
    server: ip do servidor nfs
    path: /
  accessModes:
    - ReadWriteMany
  claimRef:
    kind: PersistentVolumeClaim
    namespace: harbor
    name: harbor-jobservice-scandata
    apiVersion: v1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: harbor-nfs-sc
  volumeMode: Filesystem

  # harbor-chartmuseum
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-chartmuseum
  namespace: harbor
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: harbor-chartmuseum
  storageClassName: harbor-nfs-sc
  volumeMode: Filesystem
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-chartmuseum
spec:
  capacity:
    storage: 6Gi
  nfs:
    server: ip do servidor nfs
    path: /
  accessModes:
    - ReadWriteMany
  claimRef:
    kind: PersistentVolumeClaim
    namespace: harbor
    name: harbor-chartmuseum
    apiVersion: v1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: harbor-nfs-sc
  volumeMode: Filesystem



  # data-harbor-trivy-0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-harbor-trivy-0
  namespace: harbor
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: data-harbor-trivy-0
  storageClassName: harbor-nfs-sc
  volumeMode: Filesystem
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-harbor-trivy-0
spec:
  capacity:
    storage: 6Gi
  nfs:
    server: ip do servidor nfs
    path: /
  accessModes:
    - ReadWriteMany
  claimRef:
    kind: PersistentVolumeClaim
    namespace: harbor
    name: data-harbor-trivy-0
    apiVersion: v1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: harbor-nfs-sc
  volumeMode: Filesystem


  # data-harbor-redis-0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-harbor-redis-0
  namespace: harbor
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: data-harbor-redis-0
  storageClassName: ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-registry
  namespace: harbor
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: harbor-registry
  storageClassName: harbor-nfs-sc
  volumeMode: Filesystem
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-registry
spec:
  capacity:
    storage: 6Gi
  nfs:
    server: ip do servidor nfs
    path: /
  accessModes:
    - ReadWriteMany
  claimRef:
    kind: PersistentVolumeClaim
    namespace: harbor
    name: harbor-registry
    apiVersion: v1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: harbor-nfs-sc
  volumeMode: Filesystem
# harbor-jobservice
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-jobservice
  namespace: harbor
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: harbor-jobservice
  storageClassName: harbor-nfs-sc
  volumeMode: Filesystem
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-jobservice
spec:
  capacity:
    storage: 6Gi
  nfs:
    server: ip do servidor nfs
    path: /
  accessModes:
    - ReadWriteMany
  claimRef:
    kind: PersistentVolumeClaim
    namespace: harbor
    name: harbor-jobservice
    apiVersion: v1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: harbor-nfs-sc
  volumeMode: Filesystem


  # harbor-jobservice-scandata
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-jobservice-scandata
  namespace: harbor
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: harbor-jobservice-scandata
  storageClassName: harbor-nfs-sc
  volumeMode: Filesystem
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-jobservice-scandata
spec:
  capacity:
    storage: 6Gi
  nfs:
    server: ip do servidor nfs
    path: /
  accessModes:
    - ReadWriteMany
  claimRef:
    kind: PersistentVolumeClaim
    namespace: harbor
    name: harbor-jobservice-scandata
    apiVersion: v1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: harbor-nfs-sc
  volumeMode: Filesystem

  # harbor-chartmuseum
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-chartmuseum
  namespace: harbor
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: harbor-chartmuseum
  storageClassName: harbor-nfs-sc
  volumeMode: Filesystem
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-chartmuseum
spec:
  capacity:
    storage: 6Gi
  nfs:
    server: ip do servidor nfs
    path: /
  accessModes:
    - ReadWriteMany
  claimRef:
    kind: PersistentVolumeClaim
    namespace: harbor
    name: harbor-chartmuseum
    apiVersion: v1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: harbor-nfs-sc
  volumeMode: Filesystem



  # data-harbor-trivy-0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-harbor-trivy-0
  namespace: harbor
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: data-harbor-trivy-0
  storageClassName: harbor-nfs-sc
  volumeMode: Filesystem
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-harbor-trivy-0
spec:
  capacity:
    storage: 6Gi
  nfs:
    server: ip do servidor nfs
    path: /
  accessModes:
    - ReadWriteMany
  claimRef:
    kind: PersistentVolumeClaim
    namespace: harbor
    name: data-harbor-trivy-0
    apiVersion: v1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: harbor-nfs-sc
  volumeMode: Filesystem


  # data-harbor-redis-0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-harbor-redis-0
  namespace: harbor
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: data-harbor-redis-0
  storageClassName: harbor-nfs-sc
  volumeMode: Filesystem
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-harbor-redis-0
spec:
  capacity:
    storage: 6Gi
  nfs:
    server: ip do servidor nfs
    path: /
  accessModes:
    - ReadWriteMany
  claimRef:
    kind: PersistentVolumeClaim
    namespace: harbor
    name: data-harbor-redis-0
    apiVersion: v1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: harbor-nfs-sc
  volumeMode: Filesystem
me
metadata:
  name: data-harbor-redis-0
spec:
  capacity:
    storage: 6Gi
  nfs:
    server: ip do servidor nfs
    path: /
  accessModes:
    - ReadWriteMany
  claimRef:
    kind: PersistentVolumeClaim
    namespace: harbor
    name: data-harbor-redis-0
    apiVersion: v1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: harbor-nfs-sc
  volumeMode: Filesystem
